import { Nav } from '@/components'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Futura Service',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-sf'>
      
      <body className='bg-[#232323]'>

        <Nav/>

        <div className='p-3'>
        {children}
        </div>
        


      </body>
    </html>
  )
}
